some_another_method

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,136 +5,152 @@ echo "Compilation of R buildpack..."
 echo "by RAW21...."
 
 
-# fail fast
-set -e
+### another way
+mkdir /usr/local/src/R
+cd /usr/local/src/R
+curl -O http://cran.utstat.utoronto.ca/src/base/R-3/R-3.2.1.tar.gz
+tar xzvf R-3.2.1.tar.gz
+cd R-3.2.1
+./configure
+make
+make check
+cd ..
+rm -f R Rscript
+ln -s R-3.2.1/bin/R R
+ln -s R-3.2.1/bin/Rscript Rscript
+###
 
-# debug
-# set -x
 
-shopt -s extglob
+# # fail fast
+# set -e
 
-function error() {
-  echo " !     $*" >&2
-  exit 1
-}
+# # debug
+# # set -x
 
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";;
-    *)      sed -u "$c";;
-  esac
-}
+# shopt -s extglob
 
-function read_var() {
-  echo $(head -n 1 $1)
-}
+# function error() {
+#   echo " !     $*" >&2
+#   exit 1
+# }
 
-# clean up leaking environment
-unset GIT_DIR
+# function indent() {
+#   c='s/^/       /'
+#   case $(uname) in
+#     Darwin) sed -l "$c";;
+#     *)      sed -u "$c";;
+#   esac
+# }
 
-# parse and derive params
-BUILD_DIR=$1
-CACHE_DIR="$2/vendor"
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
-BUILDPACK_DIR="$(dirname $(dirname $0))"
-GCC_VERSION=4.8
+# function read_var() {
+#   echo $(head -n 1 $1)
+# }
 
-# # fix STACK variable if unset
-# if [ -z "${STACK}" ];
-# then
-#   STACK="cedar-14"
-# fi
-STACK="master" # "cedar-14"
+# # clean up leaking environment
+# unset GIT_DIR
 
-# config
+# # parse and derive params
+# BUILD_DIR=$1
+# CACHE_DIR="$2/vendor"
+# LP_DIR=`cd $(dirname $0); cd ..; pwd`
+# BUILDPACK_DIR="$(dirname $(dirname $0))"
+# GCC_VERSION=4.8
 
-# # read in R version if file exists
-# if [[ -f $BUILD_DIR/.r-version ]]; then
-#   R_VERSION=`read_var $BUILD_DIR/.r-version`
-# else
-#   R_VERSION="3.2.1" # "3.2.4"
-# fi
-R_VERSION="3.3.1" #"3.2.1"
+# # # fix STACK variable if unset
+# # if [ -z "${STACK}" ];
+# # then
+# #   STACK="cedar-14"
+# # fi
+# STACK="master" # "cedar-14"
 
-# # read in buildback binary version if file exists
-# if [[ -f $BUILD_DIR/.r-buildpack-version ]]; then
-#   BUILD_PACK_VERSION=`read_var $BUILD_DIR/.r-buildpack-version`
-# else
-#   BUILD_PACK_VERSION="20151119-2338" # "20160322-0811"
-# fi
-# BUILD_PACK_VERSION="20150719-0018" #"20151119-2338"
+# # config
 
-# S3_BUCKET="heroku-buildpack-r"
-R_BINARIES="https://cran.r-project.org/src/base/R-3/R-3.3.1.tar.gz" # hard coded :X
+# # # read in R version if file exists
+# # if [[ -f $BUILD_DIR/.r-version ]]; then
+# #   R_VERSION=`read_var $BUILD_DIR/.r-version`
+# # else
+# #   R_VERSION="3.2.1" # "3.2.4"
+# # fi
+# R_VERSION="3.3.1" #"3.2.1"
 
-VENDOR_DIR="$BUILD_DIR/vendor"
-CRAN_MIRROR="http://cran.revolutionanalytics.com"
+# # # read in buildback binary version if file exists
+# # if [[ -f $BUILD_DIR/.r-buildpack-version ]]; then
+# #   BUILD_PACK_VERSION=`read_var $BUILD_DIR/.r-buildpack-version`
+# # else
+# #   BUILD_PACK_VERSION="20151119-2338" # "20160322-0811"
+# # fi
+# # BUILD_PACK_VERSION="20150719-0018" #"20151119-2338"
 
-mkdir -p $CACHE_DIR
+# # S3_BUCKET="heroku-buildpack-r"
+# R_BINARIES="https://cran.r-project.org/src/base/R-3/R-3.3.1.tar.gz" # hard coded :X
 
-# # vendor R into the slug
-# echo "Vendoring R $R_VERSION for $STACK stack ($BUILD_PACK_VERSION)" | indent
-echo "Vendoring R 3.3.1" | indent
+# VENDOR_DIR="$BUILD_DIR/vendor"
+# CRAN_MIRROR="http://cran.revolutionanalytics.com"
 
-# download and unpack binaries
-echo "Downloading and unpacking R binaries ($R_BINARIES)" | indent
-curl $R_BINARIES -s -o - | tar xzf - -C .
+# mkdir -p $CACHE_DIR
 
-ls
-cd R-3.3.1
-# ./configure
-./INSTALL
+# # # vendor R into the slug
+# # echo "Vendoring R $R_VERSION for $STACK stack ($BUILD_PACK_VERSION)" | indent
+# echo "Vendoring R 3.3.1" | indent
 
-# # also using buildpack-apt?
-# if [ -d $BUILD_DIR/.apt ]; then
-#   cp -r $VENDOR_DIR/.apt/ $BUILD_DIR
-# else
-#   mv $VENDOR_DIR/.apt/ $BUILD_DIR
-# fi
+# # download and unpack binaries
+# echo "Downloading and unpacking R binaries ($R_BINARIES)" | indent
+# curl $R_BINARIES -s -o - | tar xzf - -C .
 
-# # need to copy the binaries to /app/vendor so that R works when compiling packages
+# ls
+# cd R-3.3.1
+# # ./configure
+# ./INSTALL
 
-# mkdir -p /app/.apt
-# cp -R $BUILD_DIR/.apt/* /app/.apt
+# # # also using buildpack-apt?
+# # if [ -d $BUILD_DIR/.apt ]; then
+# #   cp -r $VENDOR_DIR/.apt/ $BUILD_DIR
+# # else
+# #   mv $VENDOR_DIR/.apt/ $BUILD_DIR
+# # fi
 
-# mkdir -p /app/vendor/R
-# cp -R $VENDOR_DIR/R/* /app/vendor/R
+# # # need to copy the binaries to /app/vendor so that R works when compiling packages
 
-# # trialed and errored on this; copy over libs to gfortran, so
-# # that liblto_plugin.so and others can be found
-# # (tried using LDFLAGS, LD_LIBRARY_PATH and LIBRARY_PATH but didn't work)
-# cp -R /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/* /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION
-# # cp /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so
+# # mkdir -p /app/.apt
+# # cp -R $BUILD_DIR/.apt/* /app/.apt
 
-# # set environment variables, needed for compiling packages
-# source "$BUILDPACK_DIR/bin/r_environment.sh"
+# # mkdir -p /app/vendor/R
+# # cp -R $VENDOR_DIR/R/* /app/vendor/R
 
-# # copy over environment
-# mkdir -p $BUILD_DIR/.profile.d
-# cp "$BUILDPACK_DIR/bin/r_environment.sh" "$BUILD_DIR/.profile.d/r_environment.sh"
+# # # trialed and errored on this; copy over libs to gfortran, so
+# # # that liblto_plugin.so and others can be found
+# # # (tried using LDFLAGS, LD_LIBRARY_PATH and LIBRARY_PATH but didn't work)
+# # cp -R /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/* /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION
+# # # cp /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so
 
-# prevent warnings when building packages
-mkdir -p /app/vendor/R/lib64/R/doc/html
-touch /app/vendor/R/lib64/R/doc/html/R.css
+# # # set environment variables, needed for compiling packages
+# # source "$BUILDPACK_DIR/bin/r_environment.sh"
 
-# install dependencies from CRAN
-echo "Executing init.r script" | indent
+# # # copy over environment
+# # mkdir -p $BUILD_DIR/.profile.d
+# # cp "$BUILDPACK_DIR/bin/r_environment.sh" "$BUILD_DIR/.profile.d/r_environment.sh"
 
-# set the CRAN mirror and run the init.r program
-/app/vendor/R/bin/R -s <<RPROG > indent
-  Sys.setenv(BUILD_DIR="$BUILD_DIR")
-  setwd("$BUILD_DIR")
-  r <- getOption("repos");
-  r["CRAN"] <- "$CRAN_MIRROR";
-  options(repos=r);
-  `cat $BUILD_DIR/init.r`
-RPROG
+# # prevent warnings when building packages
+# mkdir -p /app/vendor/R/lib64/R/doc/html
+# touch /app/vendor/R/lib64/R/doc/html/R.css
 
-echo "R $R_VERSION successfully installed" | indent
+# # install dependencies from CRAN
+# echo "Executing init.r script" | indent
 
-# # need to copy binaries back so that any
-# # installed packages are included in the slug
-# rm -rf $VENDOR_DIR/R
-# mkdir -p $VENDOR_DIR/R
-# cp -R /app/vendor/R/* $VENDOR_DIR/R
+# # set the CRAN mirror and run the init.r program
+# /app/vendor/R/bin/R -s <<RPROG > indent
+#   Sys.setenv(BUILD_DIR="$BUILD_DIR")
+#   setwd("$BUILD_DIR")
+#   r <- getOption("repos");
+#   r["CRAN"] <- "$CRAN_MIRROR";
+#   options(repos=r);
+#   `cat $BUILD_DIR/init.r`
+# RPROG
+
+# echo "R $R_VERSION successfully installed" | indent
+
+# # # need to copy binaries back so that any
+# # # installed packages are included in the slug
+# # rm -rf $VENDOR_DIR/R
+# # mkdir -p $VENDOR_DIR/R
+# # cp -R /app/vendor/R/* $VENDOR_DIR/R
