modified

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -20,142 +20,139 @@ echo "by RAW21...."
 # ###
 
 
-### an another way
-curl -O https://github.com/nafiux/portableR/tarball/master | tar xzvf - -C .
-ls
-echo "R should be here..."
-###
-
-# # fail fast
-# set -e
-
-# # debug
-# # set -x
-
-# shopt -s extglob
-
-# function error() {
-#   echo " !     $*" >&2
-#   exit 1
-# }
-
-# function indent() {
-#   c='s/^/       /'
-#   case $(uname) in
-#     Darwin) sed -l "$c";;
-#     *)      sed -u "$c";;
-#   esac
-# }
-
-# function read_var() {
-#   echo $(head -n 1 $1)
-# }
-
-# # clean up leaking environment
-# unset GIT_DIR
-
-# # parse and derive params
-# BUILD_DIR=$1
-# CACHE_DIR="$2/vendor"
-# LP_DIR=`cd $(dirname $0); cd ..; pwd`
-# BUILDPACK_DIR="$(dirname $(dirname $0))"
-# GCC_VERSION=4.8
-
-# # # fix STACK variable if unset
-# # if [ -z "${STACK}" ];
-# # then
-# #   STACK="cedar-14"
-# # fi
-# STACK="master" # "cedar-14"
-
-# # config
-
-# # # read in R version if file exists
-# # if [[ -f $BUILD_DIR/.r-version ]]; then
-# #   R_VERSION=`read_var $BUILD_DIR/.r-version`
-# # else
-# #   R_VERSION="3.2.1" # "3.2.4"
-# # fi
-# R_VERSION="3.3.1" #"3.2.1"
-
-# # # read in buildback binary version if file exists
-# # if [[ -f $BUILD_DIR/.r-buildpack-version ]]; then
-# #   BUILD_PACK_VERSION=`read_var $BUILD_DIR/.r-buildpack-version`
-# # else
-# #   BUILD_PACK_VERSION="20151119-2338" # "20160322-0811"
-# # fi
-# # BUILD_PACK_VERSION="20150719-0018" #"20151119-2338"
-
-# # S3_BUCKET="heroku-buildpack-r"
-# R_BINARIES="https://cran.r-project.org/src/base/R-3/R-3.3.1.tar.gz" # hard coded :X
-
-# VENDOR_DIR="$BUILD_DIR/vendor"
-# CRAN_MIRROR="http://cran.revolutionanalytics.com"
-
-# mkdir -p $CACHE_DIR
-
-# # # vendor R into the slug
-# # echo "Vendoring R $R_VERSION for $STACK stack ($BUILD_PACK_VERSION)" | indent
-# echo "Vendoring R 3.3.1" | indent
-
-# # download and unpack binaries
-# echo "Downloading and unpacking R binaries ($R_BINARIES)" | indent
-# curl $R_BINARIES -s -o - | tar xzf - -C .
-
+# ### an another way
+# curl -O https://github.com/nafiux/portableR/tarball/master | tar xzvf - -C .
 # ls
-# cd R-3.3.1
-# # ./configure
-# ./INSTALL
+# echo "R should be here..."
+# ###
 
-# # # also using buildpack-apt?
-# # if [ -d $BUILD_DIR/.apt ]; then
-# #   cp -r $VENDOR_DIR/.apt/ $BUILD_DIR
-# # else
-# #   mv $VENDOR_DIR/.apt/ $BUILD_DIR
-# # fi
+# fail fast
+set -e
 
-# # # need to copy the binaries to /app/vendor so that R works when compiling packages
+# debug
+# set -x
 
-# # mkdir -p /app/.apt
-# # cp -R $BUILD_DIR/.apt/* /app/.apt
+shopt -s extglob
 
-# # mkdir -p /app/vendor/R
-# # cp -R $VENDOR_DIR/R/* /app/vendor/R
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
 
-# # # trialed and errored on this; copy over libs to gfortran, so
-# # # that liblto_plugin.so and others can be found
-# # # (tried using LDFLAGS, LD_LIBRARY_PATH and LIBRARY_PATH but didn't work)
-# # cp -R /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/* /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION
-# # # cp /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
 
-# # # set environment variables, needed for compiling packages
-# # source "$BUILDPACK_DIR/bin/r_environment.sh"
+function read_var() {
+  echo $(head -n 1 $1)
+}
 
-# # # copy over environment
-# # mkdir -p $BUILD_DIR/.profile.d
-# # cp "$BUILDPACK_DIR/bin/r_environment.sh" "$BUILD_DIR/.profile.d/r_environment.sh"
+# clean up leaking environment
+unset GIT_DIR
 
-# # prevent warnings when building packages
-# mkdir -p /app/vendor/R/lib64/R/doc/html
-# touch /app/vendor/R/lib64/R/doc/html/R.css
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR="$2/vendor"
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+BUILDPACK_DIR="$(dirname $(dirname $0))"
+GCC_VERSION=4.8
 
-# # install dependencies from CRAN
-# echo "Executing init.r script" | indent
+# # fix STACK variable if unset
+# if [ -z "${STACK}" ];
+# then
+#   STACK="cedar-14"
+# fi
+STACK="master" # "cedar-14"
 
-# # set the CRAN mirror and run the init.r program
-# /app/vendor/R/bin/R -s <<RPROG > indent
-#   Sys.setenv(BUILD_DIR="$BUILD_DIR")
-#   setwd("$BUILD_DIR")
-#   r <- getOption("repos");
-#   r["CRAN"] <- "$CRAN_MIRROR";
-#   options(repos=r);
-#   `cat $BUILD_DIR/init.r`
-# RPROG
+# config
 
-# echo "R $R_VERSION successfully installed" | indent
+# # read in R version if file exists
+# if [[ -f $BUILD_DIR/.r-version ]]; then
+#   R_VERSION=`read_var $BUILD_DIR/.r-version`
+# else
+#   R_VERSION="3.2.1" # "3.2.4"
+# fi
+R_VERSION="3.2.0" #"3.2.1"
 
-# # # need to copy binaries back so that any
-# # # installed packages are included in the slug
-# # rm -rf $VENDOR_DIR/R
-# # mkdir -p $VENDOR_DIR/R
-# # cp -R /app/vendor/R/* $VENDOR_DIR/R
+# # read in buildback binary version if file exists
+# if [[ -f $BUILD_DIR/.r-buildpack-version ]]; then
+#   BUILD_PACK_VERSION=`read_var $BUILD_DIR/.r-buildpack-version`
+# else
+#   BUILD_PACK_VERSION="20151119-2338" # "20160322-0811"
+# fi
+# BUILD_PACK_VERSION="20150719-0018" #"20151119-2338"
+
+# S3_BUCKET="heroku-buildpack-r"
+# R_BINARIES="https://cran.r-project.org/src/base/R-3/R-3.3.1.tar.gz" # hard coded :X
+R_BINARIES="https://github.com/RAW21/R_binary/blob/master/R-3.2.0-binaries-20150719-0018.tar.gz?raw=true"
+
+VENDOR_DIR="$BUILD_DIR/vendor"
+CRAN_MIRROR="http://cran.revolutionanalytics.com"
+
+mkdir -p $CACHE_DIR
+
+# # vendor R into the slug
+# echo "Vendoring R $R_VERSION for $STACK stack ($BUILD_PACK_VERSION)" | indent
+echo "Vendoring R 3.2.0" | indent
+
+# download and unpack binaries
+echo "Downloading and unpacking R binaries ($R_BINARIES)" | indent
+curl $R_BINARIES -s -o - | tar xzf - -C .
+
+
+# also using buildpack-apt?
+if [ -d $BUILD_DIR/.apt ]; then
+  cp -r $VENDOR_DIR/.apt/ $BUILD_DIR
+else
+  mv $VENDOR_DIR/.apt/ $BUILD_DIR
+fi
+
+# need to copy the binaries to /app/vendor so that R works when compiling packages
+
+mkdir -p /app/.apt
+cp -R $BUILD_DIR/.apt/* /app/.apt
+
+mkdir -p /app/vendor/R
+cp -R $VENDOR_DIR/R/* /app/vendor/R
+
+# trialed and errored on this; copy over libs to gfortran, so
+# that liblto_plugin.so and others can be found
+# (tried using LDFLAGS, LD_LIBRARY_PATH and LIBRARY_PATH but didn't work)
+cp -R /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/* /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION
+# cp /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so /app/.apt/usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/liblto_plugin.so
+
+# set environment variables, needed for compiling packages
+source "$BUILDPACK_DIR/bin/r_environment.sh"
+
+# copy over environment
+mkdir -p $BUILD_DIR/.profile.d
+cp "$BUILDPACK_DIR/bin/r_environment.sh" "$BUILD_DIR/.profile.d/r_environment.sh"
+
+# prevent warnings when building packages
+mkdir -p /app/vendor/R/lib64/R/doc/html
+touch /app/vendor/R/lib64/R/doc/html/R.css
+
+# install dependencies from CRAN
+echo "Executing init.r script" | indent
+
+# set the CRAN mirror and run the init.r program
+/app/vendor/R/bin/R -s <<RPROG > indent
+  Sys.setenv(BUILD_DIR="$BUILD_DIR")
+  setwd("$BUILD_DIR")
+  r <- getOption("repos");
+  r["CRAN"] <- "$CRAN_MIRROR";
+  options(repos=r);
+  `cat $BUILD_DIR/init.r`
+RPROG
+
+echo "R $R_VERSION successfully installed" | indent
+
+# # need to copy binaries back so that any
+# # installed packages are included in the slug
+# rm -rf $VENDOR_DIR/R
+# mkdir -p $VENDOR_DIR/R
+# cp -R /app/vendor/R/* $VENDOR_DIR/R
